### PR TITLE
Add curl library to imports

### PR DESCRIPTION
**Pull request by geotheory**
Package installation may fail otherwise if library isn't already present

### CODE REVIEW

**Comment by hoesler** [comment]
Thanks for your contribution, but curl is not a direct dependency and only required by V8 (http://cran.r-project.org/web/packages/V8/index.html). So I don't think it should be listed as an import.

**Comment by geotheory** [comment]
Well it's up to you.  Installation failed on my Windows machine because of it.  Perhaps worth a small note in installation instructions instead..

**Comment by hoesler** [comment]
I wanted to test your case here and realized that I don’t actually have curl installed!
V8 0.3, the version I use, doesn't require it. The dependency was introduced with 0.4.
So I think your problem might be a general R issue with dependency resolution...

Am 04.02.2015 um 16:40 schrieb Robin Edwards notifications@github.com:

**Comment by geotheory** [comment]
Ah, ok then!

**Pull request closed without merging**
